#ifndef GENERALSETTINGS
#define GENERALSETTINGS

#define LABEL_COUNTS 8
#define LABEL_COUNTS_ROWS 2

#define MARGIN_DESKTOP 50

#define FONT_SIZE 14 //24
#define FONT_PUSH_SIZE FONT_SIZE - 1

#define TEXT_ROOT_LIST "Предметы:"
#define TEXT_SHEDULE_DEFAULT "Расписание:"

#endif // GENERALSETTINGS

